CREATE DATABASE TESTEDELPHI;

CREATE TABLE TESTEDELPHI.CLIENTES(
CODIGO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL);

CREATE INDEX IX_CLIENTES ON TESTEDELPHI.CLIENTES(CODIGO, NOME);

INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Andre Materiais de Construção','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Aux Manutenção de Elevadores','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Antonio Carlos da Silva','Maua','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Carlos da Silva Oliveira','São Bernado do Campo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Sara Alvim de Oliveira','Santo Amaro','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Rosemeire Santana da Silva','Osasco','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('AI3B Projetos de Arquitetura','Rio de Janeiro','RJ');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Danilo da Vida','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Roberto de Barro Silva','Sorocaba','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Juliana Belle','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Patricia Nascimento','Lins','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Carla Figueiredo Barros','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('LMD Urbanistica Especializada','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Douglas Fabio Silva','São Jose do Rio Preto','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Bruna Gomes','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Aline Oliveira','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('KRLS Consultoria Especializada','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Gomes Bueno','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('DBAX1 Banco de Dados','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Daniela da Silva','São Paulo','SP');
INSERT INTO TESTEDELPHI.CLIENTES(NOME, CIDADE, UF)VALUES('Juliano das Neves','Campinas','SP');

CREATE TABLE TESTEDELPHI.PRODUTOS(
CODIGO INT AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(100) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL);

CREATE INDEX IX_PRODUTOS ON TESTEDELPHI.PRODUTOS(CODIGO, DESCRICAO);

INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Memoria DDR3', 150.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Memoria DDR2', 80.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Memoria DDR4', 350.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('HDD 500GB', 170.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('HDD 1TB', 400.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Cabo de Rede Cat3', 7.50);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Conector RJ45', 0.45);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Gabinete Mid', 100.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Fonte 500 Wats', 325.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Processador X7', 1052.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Processador X3', 925.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Monitor 17', 355.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Teclado USB', 30.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Mouse USB', 25.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Cabo VGA', 3.40);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Cabo HDMI', 7.20);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Placa Mãe R3', 365.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('Placa Mãe R7', 725.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('SSD 500', 450.00);
INSERT INTO TESTEDELPHI.PRODUTOS(DESCRICAO, PRECO)VALUES('SSD M2 500', 550.00);

CREATE TABLE TESTEDELPHI.PEDIDO_DADOS_GERAIS (
    NUMERO INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_EMISSAO DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CODIGO_CLIENTE INTEGER NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL);
    
ALTER TABLE TESTEDELPHI.PEDIDO_DADOS_GERAIS ADD FOREIGN KEY (CODIGO_CLIENTE) REFERENCES TESTEDELPHI.CLIENTES(CODIGO);

CREATE INDEX IX_PEDIDOS_DADOS ON TESTEDELPHI.PEDIDO_DADOS_GERAIS(NUMERO, DATA_EMISSAO);

CREATE TABLE TESTEDELPHI.PEDIDO_PRODUTOS(
	ID INTEGER auto_increment primary KEY,
    NUMERO_PEDIDO INTEGER NOT NULL,
    CODIGO_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL);
    
ALTER TABLE TESTEDELPHI.PEDIDO_PRODUTOS ADD CONSTRAINT FK_NUMEROPEDIDO FOREIGN KEY (NUMERO_PEDIDO) REFERENCES TESTEDELPHI.PEDIDO_DADOS_GERAIS(NUMERO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TESTEDELPHI.PEDIDO_PRODUTOS ADD FOREIGN KEY (CODIGO_PRODUTO) REFERENCES TESTEDELPHI.PRODUTOS(CODIGO);

CREATE INDEX IX_PEDIDOS_DADOS ON TESTEDELPHI.PEDIDO_PRODUTOS(NUMERO_PEDIDO, ID);
